#!/usr/bin/env bash

set -e

host="$1"
repo="github:name-snrl/nixos-configuration"
ref="$repo#$host"

rm -f /etc/nix/nix.conf
nix build \
    -o /etc/nix/nix.conf \
    --extra-experimental-features 'nix-command flakes' \
    "$repo#nixosConfigurations.$host.config.environment.etc.\"nix/nix.conf\".source"
systemctl restart nix-daemon.service

nix run github:nix-community/disko/latest#disko -- --mode disko --flake "$ref"

nixos-install --no-channel-copy --no-root-password --flake "$ref"
