#!/usr/bin/env bash

set -e

service="https://0x0.st"

bold='\033[0;1m'
bold_red='\033[1;31m'
red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
nc='\033[0m'

script_name="$(basename "$0")"
[[ ! $* && -t 0 ]] && {
    echo -e "${bold}Usage:${nc}"
    echo -e "  $script_name path/to/file.txt"
    echo -e "  echo hello | $script_name"
    exit
}

load() {
    if [[ ! -t 0 ]]; then
        if [[ $* ]]; then
            echo -e "${yellow}Stdin data will be loaded:${nc}" >&2
        fi
        curl -#F file=@- "$service"
    elif [[ -f $* ]]; then
        curl -#F file=@"$*" "$service"
    elif [[ ! -f $* ]]; then
        echo -e "${bold_red}$script_name:${red} The argument must be a single regular file${nc}" >&2
        exit 1
    else
        echo -e "${bold_red}$script_name:${red} Unexpected error${nc}" >&2
        exit 1
    fi
}

result=$(load "$*")
echo -e "${bold}Response:${nc} $result"
if [[ $result =~ ^"$service"/[[:alnum:]_+-]{4} ]] && wl-copy "$result" &>/dev/null; then
    echo -e "${green}Copied to clipboard!${nc}"
else
    echo -e "${red}Failed to copy to clipboard ;(${nc}"
fi
